# -*- coding: utf-8 -*-
"""probe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jr7hNe-1qbgPGuExqmYVQBIVQvXDVuT3
"""

my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
song = my_favorite_songs
i = 0
reverse = False
ss = ''
while i < len(song):
  if song[i] != ',':      
    i += 1
    if i == len(song):
      if reverse == True:
        song = song[::-1]       
      print(song)
  else: 
    if reverse == True:
      ss = song[0:i-1]
      ss = ss[::-1]
      song = song[i+1:]      
      reverse = False
    else:
      ss = song[0:i]
      song = song[i+2:]         
      reverse = True    
    print(ss)
    song = song[::-1]  
    i = 0