# -*- coding: utf-8 -*-
"""Индексация_Вывод_песен.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ahw-sVo6wZyGRlzRIZ8F-E-Ybe4euCn9
"""

my_favorite_songs = 'Waste a Moment, Staying\' Alive, A Sorta Fairytale, Start Me Up, New Salvation'
list1 = []
i = 0
song1 = ''
length = len(my_favorite_songs)
#Записываем песни из строки в массив
while i < length:  
  if my_favorite_songs[i] != ',':
    song1 += my_favorite_songs[i]
    i += 1 
    if i == length:
      list1.append(song1)     
  else:    
    list1.append(song1) 
    song1 = ''
    i += 2  

#Выводим содержимое массива в их нормальном порядке
len1 = len(list1)  
print('В нормальном порядке')
for i in range(len1):
  print(i, list1[i])

#Выводим содержимое массива в заданном порядке 
print('')  
print('В заданном порядке')
i = 0
j = len1 - 1
k = 0  
up = True
while k < len1:  
  if up:    
    print(list1[i])
    i += 1
    up = False
  else:
    print(list1[j])
    j -= 1
    up = True
  k += 1