# -*- coding: utf-8 -*-
"""Операции_со_списками.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4knYXoGkeFatZXvoJ14rh3qWXGTLIXL
"""

city = ['Moscow', 'Vasjuki', 'Rome', 'Paris']
citizen = [10, 1, 5, 6]
print('Население г.'+ city[1]+' -', citizen[1], 'млн.чел')
i = qnty = 0
while i < len(citizen):
  qnty += citizen[i]
  i += 1
print('Население всего ',qnty,' млн.чел')
food = ['Картофель','Горошек','Рис','Хлеб']
fruits = ['Яблоко','Апельсин','Клубника']
food.insert(2,'Рыба')
food.extend(fruits)
food.remove('Картофель')
print(food)
print('Номер Хлебa ', food.index('Хлеб'))
print('Номер Апельсина ', food.index('Апельсин'))

rec_time = 0
allsongs =[['song1',2],['song2',2.3],['song3',4],['song4', 2.1],['song5',2],['song5',2.3],['song6',2.3]]
song=allsongs[::2]
print(song)
i = 0
print('Песни', end = ' ')
while i < 3:
  rec_time += song[i][1]
  print(song[i][0], end = ' ') 
  i += 1
print('звучат', rec_time, 'мин')

